\documentclass[10pt,english]{article}
\usepackage[paperwidth=164mm, paperheight=280mm, top=19mm, bottom=19mm, left=1cm, right=1cm]{geometry} % 16:9 three pages in a row
\usepackage[english]{babel}
\usepackage{longtable}
\usepackage{fontspec}
\usepackage{booktabs}
\usepackage{hyperref}
\usepackage{varioref} %% vref
\usepackage{paralist} %% compactenum
\usepackage{siunitx} %% \num
\usepackage{IEEEtrantools} % proper indentation for multi-line equations
\usepackage{amsmath} %% \pmatrix
\usepackage{subfig}
\usepackage{apacite}

%% make a single « start and end a chunk of \texttt{}, and two «« to represent the literal «.
\catcode`«=\active
\def«#1«{\texttt{#1}}

\begin{document}

% This chunk is needed to make sure evaluation is taking place in the current directory. The other settings are nice but not as important.
<<setup.outer, echo=FALSE, tidy=FALSE, message=FALSE>>=
library(knitr)
opts_chunk$set(results='hide', cache=TRUE, echo=TRUE, warning=TRUE, fig.width=4, fig.height=4, fig.pos = 'htb', tidy.opts=list(blank=FALSE, width.cutoff=50), background='white', tidy=TRUE, error=TRUE, message=FALSE, dev="png", dpi = 200, autodep = TRUE)
opts_knit$set(root.dir = ".")
options(scipen=999)
@

<<setup.dir, echo=FALSE, tidy=FALSE, message=FALSE>>=
## SNIC
if(file.exists("/mimer/NOBACKUP/groups/globalpoverty1/hans")){
    my.dir <- "/mimer/NOBACKUP/groups/globalpoverty1/hans/global-living-conditions"
    ## "africa-lowres.RData"
    africa.map.path <- "~/"
    max.size = 9000000000
    ## "GDL-Subnational-GDI-data.csv", "GDL Shapefiles V6.4"
    gdl.path <- "/mimer/NOBACKUP/groups/globalpoverty1/hans/global-living-conditions/"
    path.to.python <- "/usr/bin/python3"
}
## 245
if(file.exists("/media/sf_Our_data/Data/DHS")){
    my.dir <- "/media/sf_Our_data/Data/DHS"
    africa.map.path <- "~/annex/projekt/child-poverty/statiska-eller-stora-filer/"
    max.size = 2000000000
    gdl.path <- "~/annex/projekt/global-living-conditions/stora-eller-statiska-filer/"  
}
if(file.exists("~/mnt/poverty/media/sf_Our_data/Data/DHS")){
    ## Laptop
    my.dir <- "~/mnt/poverty/media/sf_Our_data/Data/DHS"
    africa.map.path <- "~/annex/projekt/child-poverty/statiska-eller-stora-filer/"
    max.size = NULL
    gdl.path <- "~/annex/projekt/global-living-conditions/stora-eller-statiska-filer/"  
}
if(Sys.info()["sysname"] == "Windows"){
    path.to.python <- "C:/Users/hanse/miniconda3/python.exe"
} 

@

\section{Install software}
To compile this document, including rendering the graphs, a working «R« and «Python/PYMC« installation is assumed. If run a on High-performance computing (HPC) cluster with restrictions on software installation that inhibits on the fly installation of needed «R« and «Python« packages, make sure the following packages are installed.

<<install.packages, cache = FALSE>>=
## Install necessary R packages
required.packages <- c("lme4", "data.table", "xtable", "effects", "parallel", "future", "doFuture", "foreach", "sf", "terra", "parallelly", "cooltools", "raster", "formatR", "lwgeom", "autoFRK", "rnaturalearthdata", "rnaturalearth", "spatstat.geom", "spatstat.random", "reticulate", "devtools", "car")
for(package in required.packages){
    if(!require(package, character.only=TRUE)){
        install.packages(package, character.only=TRUE)
    }
}
@

The following libraries are required: numpy, pandas, pickle, random, os, jax, pymc, arviz, patsy.

\section{Prepare data}
Download and standardize data with the R package «globallivingconditions«. Construct the variables «woman.exposed.to.IPV«, «woman.thinks.IPV.can.be.justified« and «man.thinks.\-IPV.can.be.justified«. Based on «woman.thinks.IPV.can.be.justified« and the sampling structure, create «justifyIPV\_cluster«. In a similar vein, construct the variable «viol01\_cluster« based on «woman.exposed.to.IPV«.

Create the following variables: «beat01\_couple« (attitude to IPV), «iliterate\_couple«, «decide2\_health« (how are decisions made about health care for the woman), «decide2\_purchases« (how are decisions made about large purchase), «edudeviation« (difference in education in the couple) , «iwi2« (wealth level of the household), «lnage\_wife« (the age of the wife, logarithm), «ln\_numb\_of\_children« (number of children, logarithm), «gdi\_s« (gender index at the regional level), «gni\_s« (estimated gross national income at the regional level).

«beat01\_couple« is a classification of the couples into one of the four possible combinations of attitudes to IPV by the wife and the husband in the couple:

\begin{compactenum}
\item No one accepts IPV 
\item Wife accepts IPV 
\item Husband accepts IPV 
\item Both accept IPV 
\end{compactenum}

It is based on the following five questions, encoded in 10 variables (5 for the husband and 5 for the man), based on the the following statment:

``In your opinion, is a husband justified in hitting or beating his wife in the following situations:''

The table below show which variable encodes the answer from the man and the woman respectively for each hypothetical situation.
\begin{table}
  \begin{centering}
  \begin{tabular}{lll}
    \toprule
    Question & Women & Men \\
    \midrule
    If she goes out without telling him? & V744A & MV744A \\
    If she neglects the children? & V744B & MV744B \\
    If she argues with him? & V744C & MV744C \\
    If she refuses to have sex with him? & V744D & MV744D \\
    If she burns the food? & V744E & MV744E \\
    \bottomrule
  \end{tabular}
  \caption{The scenarios used to query both women and men about if IPV can be justified.}
\end{centering}
\end{table}


\begin{description}
\item[«beat01\_couple«] Match couples via «V034« for women and «PersonID.unique« for men, four different levels representing the four possible combinations of two boolean variables.
\item[«decide2\_health«] Encode how decisions on health care for the wife are made based on «(M)V744A«. Combine all sorts of disagreements into one level. Discard couples that agree on the very unusual option: ``Some else decides'' (only recorded in 1 in 1000 couples for health care for the wife).
\item[«decide2\_purchases«] Same as for health decisions but based on «(M)V744B«
\item[«edudeviation«] The education level of the husband «(MV149)« compared to the educational level of the wife.

\end{description}

Also add GDI and HDI subnational data from the \href{Global Data Lab}{https://globaldatalab.org/shdi/table/sgdi/} (For now, use manually downloaded local CSV-files and map our GIS points to their Shapefiles, but when their package is fixed, use that instead of local files).

<<load.data.from.scratch>>=
library(devtools)
install_bitbucket(repo = "hansekbrand/iwi", upgrade = "never")
install_bitbucket(repo = "hansekbrand/DHSharmonisation", ref="debug", upgrade = "never")
library(globallivingconditions)
load("~/user_credentials_dhs.RData") # a list with two named elements:
                                   # "dhs.user" and "dhs.password" 
my.dt <- download.and.harmonise(
    dhs.user=credentials$dhs.user,
    dhs.password=credentials$dhs.password,
    vars.to.keep = NULL,
    file.types.to.download = c("PR", "GE", "IR", "MR", "KR"),
    waves = list("Afghanistan" = "71", "Angola" = "71", "Armenia" = "72", "Benin" = "71", "Burkina Faso" = "81", 
                 "Cambodia" = c("73", "82"), "Cameroon" = "71", "Colombia" = "72",
                 "Cote d'Ivoire" = "81", "Dominican Republic" = "61", "Ethiopia" = "71", "Haiti" = "71",
                 "Gabon" = "71", "Gambia" = "81", "Ghana" = "8C", "Guinea" = "71", "India" = c("74", "7E"),
                 "Jordan" = "74", "Kenya" = "72", "Liberia" = "7A", "Madagascar" = "81", "Maldives" = "71",
                 "Malawi" = "7A", "Mali" = "7A", "Mauritania" = "71", "Mozambique" = "62", "Myanmar" = "71",
                 "Nepal" = "7H", "Nigeria" = "7B", "Pakistan" = "71", "Papua New Guinea" = "71", "Rwanda" = "81",
                 "Sierra Leone" = "7A", "South Africa" = "71", "Tanzania" = "7B", "Togo" = "61", "Zambia" = "61",
                 "Zimbabwe" = "72"),
    variable.packages = c("wealth", "empowerment", "matching"),
    max.file.size.for.parallelisation = max.size,
    directory = my.dir,
    check.dhs.for.more.data = FALSE
)

## Domestic Violence
my.dt[ , woman.exposed.to.IPV := apply(my.dt[, list(empowerment.D106, empowerment.D107, empowerment.D108), ], 1, any), ]
my.dt[ , woman.thinks.IPV.can.be.justified := apply(my.dt[, list(empowerment.V744A, empowerment.V744B, empowerment.V744C, empowerment.V744D, empowerment.V744E), ], 1, any), ]
my.dt[ , man.thinks.IPV.can.be.justified := apply(my.dt[, list(empowerment.MV744A, empowerment.MV744B, empowerment.MV744C, empowerment.MV744D, empowerment.MV744E), ], 1, any), ]

## Keep only cases with data on at least one of our focal variables
my.dt <- my.dt[which(is.na(woman.exposed.to.IPV) == FALSE |
                     is.na(woman.thinks.IPV.can.be.justified) == FALSE |
                     is.na(man.thinks.IPV.can.be.justified) == FALSE), ]

gc(verbose = FALSE)

contextuals.f <- function(var.name, my.dt){
    ## make var.name a binary variable
    my.dt$source.var <- ifelse(my.dt[[var.name]] == 1, TRUE, FALSE)

    n.true.by.cluster <- my.dt[, list(n.true = length(which(source.var))), by = ClusterID]
    n.no.na.by.cluster <- my.dt[, list(total.n = length(which(! is.na(source.var)))), by = ClusterID]
    my.dt.2 <- merge(n.no.na.by.cluster, n.true.by.cluster)
    ## what to do with the cluster with only a single observation? Are these observations part of a cluster at all?
    ## discard them
    ## my.dt.2 <- my.dt.1[total.n > 1, ]
    ## there are three cases: 0; 0 < n.true < total.n; n.true == total.n
    ## only in the middle case, we need to calculate something
    these.have.zero.true.cases <- which(my.dt.2$n.true == 0)
    these.have.only.true.cases <- which(my.dt.2$n.true == my.dt.2$total.n)
    clusters.with.disagreement <- my.dt.2[which(! (my.dt.2$n.true == 0 | (my.dt.2$n.true == my.dt.2$total.n))), ]
    
    ## head(clusters.with.disagreement)
    ## Key: <ClusterID>
    ##                                  ClusterID total.n n.true
    ##                                     <fctr>   <int>  <int>
    ## 1: IA.Andaman And Nicobar Islands.74.10082       8      2
    ## 2: IA.Andaman And Nicobar Islands.74.10090       8      1
    ## 3: IA.Andaman And Nicobar Islands.74.10183       8      2
    
    ## the two possible manipulations are:
    ## decrease total.n by 1
    ## decrease n.true by 1 and total.n by 1
    
    ## save two dataset, one where total.n is decreased by one (ego had FALSE, so removing ego from the total did not change the n.true)
    ## the other one with the double manipulation.
    
    ego.was.false <- clusters.with.disagreement[, list(ClusterID, average.without.ego = n.true / (total.n - 1)), ]
    ego.was.true <- clusters.with.disagreement[, list(ClusterID, average.without.ego = (n.true - 1) / (total.n - 1)), ]
    my.all.true <- my.dt.2[these.have.only.true.cases, list(ClusterID, average.without.ego = 1), ]
    my.all.false <- my.dt.2[these.have.zero.true.cases, list(ClusterID, average.without.ego = 0), ]
    
    ClusterID.data.ego.was.true.disagree <- my.dt[which(ClusterID %in% clusters.with.disagreement$ClusterID & source.var), list(ClusterID, PersonID.unique, source.var), ]
    ClusterID.data.ego.was.false.disagree <- my.dt[which(ClusterID %in% clusters.with.disagreement$ClusterID & ! source.var), list(ClusterID, PersonID.unique, source.var), ]
    
    ## prepare merging
    setkey(ClusterID.data.ego.was.true.disagree, ClusterID)
    setkey(ClusterID.data.ego.was.false.disagree, ClusterID)
    
    my.true.disagreement <- merge(ClusterID.data.ego.was.true.disagree, ego.was.true)
    my.false.disagreement <- merge(ClusterID.data.ego.was.false.disagree, ego.was.false)
    
    ## agreement
    ClusterID.data.ego.was.true.agree <- my.dt[which(! ClusterID %in% clusters.with.disagreement$ClusterID & source.var), list(ClusterID, PersonID.unique, source.var), ]
    ClusterID.data.ego.was.false.agree <- my.dt[which(! ClusterID %in% clusters.with.disagreement$ClusterID & ! source.var), list(ClusterID, PersonID.unique, source.var), ]
    
    ## prepare merging
    setkey(ClusterID.data.ego.was.true.agree, ClusterID)
    setkey(ClusterID.data.ego.was.false.agree, ClusterID)
    
    my.true.agreement <- merge(ClusterID.data.ego.was.true.agree, my.all.true)
    my.false.agreement <- merge(ClusterID.data.ego.was.false.agree, my.all.false)
    
    temp.1 <- rbind(my.true.agreement, my.false.agreement, my.true.disagreement, my.false.disagreement)
    temp.2 <- temp.1[, list(PersonID.unique, average.without.ego)]
    colnames(temp.2)[2] <- "average.without.ego"
    setkey(temp.2, PersonID.unique)
    return(temp.2)
}

justifyIPV_cluster <- contextuals.f("woman.thinks.IPV.can.be.justified", my.dt)
viol01_cluster <- contextuals.f("woman.exposed.to.IPV", my.dt)
setkey(my.dt, PersonID.unique)

for(x in c("justifyIPV_cluster", "viol01_cluster")){
    my.cluster.var <- get(x)
    colnames(my.cluster.var)[2] <- x
    my.dt <- merge(my.dt, my.cluster.var, all.x = TRUE, all.y = FALSE)
}

## match partners in a household by using matching V034 for women with PersonID.unique for men.
## empowerment.V034 contains the line number of the husband
## my.map records, for women with a husband, the index number of the man's record
## subset with that index number to add a feature of the husband onto the record of the wife.
my.map <- my.dt[, match(paste(HouseholdID, empowerment.V034, sep = "."), PersonID.unique), ]
my.dt[, husband.thinks.IPV.can.be.justified := man.thinks.IPV.can.be.justified[my.map], ]
my.dt[which(woman.thinks.IPV.can.be.justified &
            husband.thinks.IPV.can.be.justified),
      beat01_couple := "Both justify IPV", ]
my.dt[which(! woman.thinks.IPV.can.be.justified &
            ! husband.thinks.IPV.can.be.justified),
      beat01_couple := "No one justifys IPV", ]
my.dt[which(! woman.thinks.IPV.can.be.justified &
            husband.thinks.IPV.can.be.justified),
      beat01_couple := "Husband justifys IPV", ]
my.dt[which(woman.thinks.IPV.can.be.justified &
            ! husband.thinks.IPV.can.be.justified),
      beat01_couple := "Wife justifys IPV", ]

## How are decisions on made?
decisions.f <- function(answer.from.wife, answer.from.husband){
    results <- rep(NA, length(answer.from.wife))
    results[which(answer.from.wife == "Respondent and husband/partner" &
                  answer.from.husband == "Respondent and wife/partner")] <- "joint decisions"
    results[which(answer.from.wife == "Respondent alone" &
                  answer.from.husband == "Wife/partner alone")] <- "wife decides"
    results[which(answer.from.wife == "Husband/partner alone" &
                  answer.from.husband == "Respondent alone")] <- "husband decides"
    ## Wife says I decide, husband says something else
    results[which(answer.from.wife == "Respondent alone" &
                  answer.from.husband != "Wife/partner alone")] <- "don't agree"
    ## Wife says my husband decides, husband says something else
    results[which(answer.from.wife == "Husband/partner alone" &
                  answer.from.husband != "Respondent alone")] <- "don't agree"
    ## Wife says we decide together, partners says something else
    results[which(answer.from.wife == "Respondent and husband/partner" &
                  answer.from.husband != "Respondent and wife/partner")] <- "don't agree"
    ## Wife says Someone else decide, partners says something else
    results[which(answer.from.wife == "Someone else" &
                  answer.from.husband != "Someone else")] <- "don't agree"
    ## Wife OR husband says "Respondent and other person"
    results[which(answer.from.wife == "Respondent and other person" |
                  answer.from.husband == "Respondent and other person")] <- "don't agree"
    return(results)
}

## How are decisions made on health care and large purchases
my.dt[, decide2_health := decisions.f(empowerment.V743A, empowerment.MV743A[my.map]), ]
my.dt[, decide2_purchases := decisions.f(empowerment.V743B, empowerment.MV743B[my.map]), ]

## Educational differences: edudeviation
## Make V149 and MV149 ordered factors with this ordering
education.levels.ordered <- c("No education", "Incomplete primary", "Complete primary", "Incomplete secondary", "Complete secondary", "Higher")
my.dt[ , empowerment.V149 := factor(empowerment.V149, levels = education.levels.ordered, ordered = TRUE), ]
my.dt[ , empowerment.MV149 := factor(empowerment.MV149, levels = education.levels.ordered, ordered = TRUE), ]
my.dt[which(empowerment.V149 == empowerment.MV149[my.map]), edudeviation := "No difference", ]
my.dt[which(as.numeric(empowerment.V149) < as.numeric(empowerment.MV149[my.map])), edudeviation := "Husband has higher edu.", ]
my.dt[which(as.numeric(empowerment.V149) > as.numeric(empowerment.MV149[my.map])), edudeviation := "Wife has higher edu.", ]

## ln_numb_of_children, 
## Björns original used BORDX which includes dead children.
my.dt[ , ln_numb_of_children := log(0.5 + apply(cbind(empowerment.V202, empowerment.V203, empowerment.V204, empowerment.V205), 1, sum)), ]

my.dt[ , lnage_wife := log(age), ]

## Construct the literacy of the couple
my.dt[ , man.is.illiterate := ifelse(car::recode(empowerment.MV155, recodes = "c('Cannot read at all', 'Blind/visually impaired', 'Vision problems') = TRUE; c('Able to read only parts of sentence', 'Able to read whole sentence') = FALSE; c('No card with required language', 'No card with required language/visually impaired') = NA") == "TRUE", TRUE, FALSE), ]

my.dt[, wife.is.illiterate := ifelse(car::recode(empowerment.V155, recodes = "c('Able to read only parts of sentence', 'Able to read whole sentence', 'Reads easily', 'Reads with difficulty') = 0; c('Cannot read at all', 'Blind/visually impaired', 'Cannot read at all', 'Vision problems', 'Blind / visually impaired', 'Cannot see/Blind', 'Blind, cannot see well', 'No card with required language/Visually impaired') = 1; 'No card with required language' = NA") == 1, TRUE, FALSE), ]

my.dt[, husband.is.illiterate := man.is.illiterate[my.map], ]

my.dt[, couple_is_illiterate := factor(rep(NA, nrow(my.dt)), levels = c("No one can read", "Only husband can read", "Only wife can read", "Both can read")), ]
my.dt[which(husband.is.illiterate & wife.is.illiterate), couple_is_illiterate := "No one can read", ]
my.dt[which(husband.is.illiterate & (wife.is.illiterate == FALSE)), couple_is_illiterate := "Only wife can read", ]
my.dt[which((husband.is.illiterate == FALSE) & wife.is.illiterate), couple_is_illiterate := "Only husband can read", ]
my.dt[which((husband.is.illiterate == FALSE) & (wife.is.illiterate == FALSE)), couple_is_illiterate := "Both can read", ]
## clean up
my.dt[, man.is.illiterate := NULL, ]
my.dt[, husband.is.illiterate := NULL, ]
my.dt[, wife.is.illiterate := NULL, ]

## use only the totals from GDL.
gdi <- setDT(read.csv(paste0(gdl.path, "GDL-Subnational-GDI-data.csv"), check.names = FALSE))
## keep only the necessary columns from hdi and gdi
## GDI has no data in columns "older" than 2000
my.cols <- c("GDLCODE", 2000:2022)
gdi.clean <- gdi[ , my.cols, with = FALSE]

## convert gdi.clean from wide to lon
# Convert to long format
gdi.long <- melt(gdi.clean, id.vars = "GDLCODE", 
                variable.name = "year.of.interview", 
                value.name = "GDI")
gdi.long[, year.of.interview := as.numeric(as.character(year.of.interview)), ]

## impute data for years not estimated by GDL.
## To improve imputations, add country as a variable so that subregions share 
## the same country
## gdi.long[, country := factor(substring(GDLCODE, 1, 3)), ]
## gdi.long$GDLCODE <- factor(gdi.long$GDLCODE)
## imp.model.gdi <- mice::mice(gdi.long, method = "pmm", m = 1, printFlag = FALSE)
## gdi.long.complete <- mice::complete(imp.model.gdi)
## data.table::setDT(gdi.long.complete)
## gdi.long <- gdi.long.complete

## Now that we know which GLDCODE for which coordinate, create a data set with ClusterID, coordinates, and year, and add the GDL data to that set.

## Use the GDL code that corresponds to the "total" version for the country.
my.temp.set <- unique(my.dt[, list(ClusterID, year.of.interview, GDLCODE = paste0(globallivingconditions::iso.3166$String.code[match(country.code.ISO.3166.alpha.3, globallivingconditions::iso.3166$numeric)], "t")), ])

setkey(my.temp.set, GDLCODE, year.of.interview)
setkey(gdi.long, GDLCODE, year.of.interview)
my.temp.set.3 <- merge(my.temp.set, gdi.long)

## Repeat with GNI
## Gross National Income per Capita in 1000 US-Dollars (2011 PPP)
gni <- setDT(read.csv(paste0(gdl.path, "GDL-Log-Gross-National-Income-per-capita-in-1000-US-Dollars-(2011-PPP)-data.csv"), check.names = FALSE))
gni.clean <- gni[ , my.cols, with = FALSE]
gni.long <- melt(gni.clean, id.vars = "GDLCODE", 
                variable.name = "year.of.interview", 
                value.name = "GNI")
gni.long[, year.of.interview := as.numeric(as.character(year.of.interview)), ]

## ## impute data for years not estimated by GDL.
## imp.model.gni <- mice::mice(gni.long, method = "pmm", m = 1, printFlag = FALSE)
## gni.long.complete <- mice::complete(imp.model.gni)
## data.table::setDT(gni.long.complete)
## gni.long <- gni.long.complete

setkey(gni.long, GDLCODE, year.of.interview)
my.temp.set.4 <- merge(my.temp.set.3, gni.long)

## If GDLCODE is no longer useful, drop it
my.temp.set.4[, GDLCODE := NULL, ]

## merge back to my.dt
setkey(my.temp.set.4, ClusterID, year.of.interview)
setkey(my.dt, ClusterID, year.of.interview)
my.dt.temp <- merge(my.dt, my.temp.set.4)

## rename columns to match previous data file
colnames(my.dt.temp) <- gsub("woman.exposed.to.IPV", "viol01_wife", colnames(my.dt.temp))
colnames(my.dt.temp) <- gsub("iwi", "iwi2", colnames(my.dt.temp))
colnames(my.dt.temp) <- gsub("ClusterID", "cluster1", colnames(my.dt.temp))
colnames(my.dt.temp) <- gsub("GDI", "gdi_s", colnames(my.dt.temp))
colnames(my.dt.temp) <- gsub("GNI", "gni_s", colnames(my.dt.temp))
colnames(my.dt.temp) <- gsub("empowerment.V149", "v149", colnames(my.dt.temp))

## Convert the country code from numeric to letters
my.dt.temp[, country := factor(globallivingconditions::iso.3166$String.code[match(country.code.ISO.3166.alpha.3, globallivingconditions::iso.3166$numeric)]), ]

## ## Remove data that appears to be artifacts rather than real data
## ## viol01_wife
## What is wrong with these? Honduras, Moldova and Timor-Leste
## HND                         1.0000000 0.00000000  3304
## MDA                         1.0000000 0.00000000   939
## Guinea has only missing,
## Mozambique has only non exposed, can't be right.

my.dt.temp <- my.dt.temp[which(country %in% c("HND", "MDA", "MOZ", "GIN") == FALSE), ]

## Use the string instead of the digit code, so we get more informative labels
my.dt.temp[, country := factor(globallivingconditions::iso.3166$String[match(country.code.ISO.3166.alpha.3, globallivingconditions::iso.3166$numeric)]), ]

## keep only the needed columns. Keep incomplete cases so that we can
## calculate the number of women who answered the questions that the
## kriging analyses is based on. Kriging requires coordinates, but it
## does not require data on exposure. Regression on the other hand do
## not require coordinates, but do require exposure data.

my.dt.clean <- my.dt.temp[which(is.na(beat01_couple) == FALSE &
                                is.na(viol01_wife) == FALSE &
                                is.na(justifyIPV_cluster) == FALSE &
                                is.na(v149) == FALSE &
                                is.na(edudeviation) == FALSE &
                                is.na(decide2_purchases) == FALSE &
                                is.na(decide2_health) == FALSE &
                                is.na(iwi2) == FALSE &
                                is.na(ln_numb_of_children) == FALSE &
                                is.na(couple_is_illiterate) == FALSE &
                                is.na(lnage_wife) == FALSE &
                                is.na(gni_s) == FALSE &
                                is.na(gdi_s) == FALSE
                                ),                                
                          list(viol01_wife, beat01_couple, v149, edudeviation, decide2_purchases, decide2_health, gdi_s, gni_s, viol01_cluster, justifyIPV_cluster, iwi2, country, cluster1, ln_numb_of_children, lnage_wife, couple_is_illiterate), ]

## z-standardize some numeric variables
for(var in c("gni_s", "iwi2", "gdi_s")){
    my.dt.clean[[var]] <- scale(my.dt.clean[[var]])
}

## Treat the states of India as countries (note that they already have separate values for GDI and GNI, the country change only affects the random intercept).
these <- which(my.dt.clean$country == "India")
if(length(these) > 0){
    my.dt.clean$country[these] <- as.vector(sapply(as.character(my.dt.clean$cluster1[these]), function(x) {
        strsplit(x, ".", fixed = TRUE)[[1]][2]
    }))
}

## TODO: Use Subnational GNI and GDI in India too, use Björns work to match Indian "countries" with GDLCODEs

## Make factors, so that the levels are clear
for(var in names(which(sapply(my.dt.clean, class) == "character"))){
    my.dt.clean[[var]] <- factor(my.dt.clean[[var]])
}

write.csv(my.dt.clean, file = "ipv-women-no-gis-matching.csv", row.names = FALSE)
save(my.dt.clean, file = "my.dt.clean.RData")

## Create the two sets needed for kriging: these need to have
## non-missing on lon, lat, but justifyIPV_cluster does not require
## the cases to have non-missing on viol01_cluster. Since
## justifyIPV_cluster is asked in more surveys, use that extra data!

justifyIPV_cluster <- my.dt[which(! is.na(lon) & ! is.na(justifyIPV_cluster)), list(country.code.ISO.3166.alpha.3, lon, lat, justifyIPV_cluster), ]
viol01_cluster <- my.dt[which(! is.na(lon) & ! is.na(viol01_cluster)), list(country.code.ISO.3166.alpha.3, lon, lat, viol01_cluster), ]

@

Start python.

<<python.avoid.startup.bug, echo = FALSE>>=
knitr::opts_chunk$set(python.reticulate=TRUE)
library(reticulate)
reticulate::use_python(path.to.python, required = TRUE)
## use_virtualenv("/mimer/NOBACKUP/groups/globalpoverty1/hans/.my-venv")
reticulate::py_run_string("import pymc as mc")
@ 

Import python modules.

<<python.1, engine='python', engine.path = path.to.python, echo = TRUE, results = "markup">>=
import pandas as pd
import pymc as pm
import pymc.sampling.jax
import numpy as np
import pickle
from patsy import dmatrix
import random
random.seed(9)

import os
os.environ["XLA_PYTHON_CLIENT_ALLOCATOR"] = "platform"

import jax

@

Load the data from a «CSV«-file. % Prepare a slice to print since actual printing works better in R.

<<splines-load.data, engine='python', warnings = TRUE, results = 'markup', cache = TRUE>>=
df = pd.read_csv("ipv-women-no-gis-matching.csv", low_memory=False)
df.shape[0]
@

Drop all rows with NA in any column.

<<splines-drop-na, engine='python', warnings = TRUE, results = 'markup', cache = TRUE>>=
df = df.dropna().reset_index(drop=True)
df.head()
@

Did we really drop any cases?

<<splines-dropped-cases, engine='python', warnings = TRUE, results = 'markup', cache = TRUE>>=
df.shape[0]
@

Print a slice of the data, some of the most important dependent variables («beat01\_couple« and «justifyIPV\_cluster«), and the variables that have information about the structure of the sample («country« and «cluster1«).

\begin{mdframed}[frametitle={Technical note: extract a slice from a pandas data.frame}]
\href{https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iloc.html}{«iloc()«} is used to specify which rows and which columns of a dataframe that you want the values of. %% Note that the object «my\_tab«, an object created by «python«, is available to R via the «py« object, created by «reticulate«.

\href{https://numpy.org/doc/stable/reference/generated/numpy.hstack.html}{«stack()«} concatenates 1D-arrays along the first dimension, while \href{https://docs.python.org/3/library/stdtypes.html#range}{«range()«} generates a list of numbers starting from its first argument until, but not including, is second argument.

The line below extract the firsts 3 rows, that is done by the part «:3« to the left of the comma, and columns 3, 4, 6, 17 and 18. Both rows and columns use zero-based indices, so the first row is row 0 and the first column is column 0.

<<splines-prepare-table, engine='python', warnings = TRUE, results = 'markup', cache = TRUE>>=
my_tab = df.iloc[:3, np.hstack((range(2, 4), 6, range(7, 9)))]
@

\end{mdframed}

<<splines-load-xtable, echo = FALSE, cache = TRUE>>=
library(xtable)
@

% «my\_tab« is recorded as a field in the variable «py«, and than thus be accessed by «R« via «py\$my\_tab«, and in the R chunk below, «xtable()« is used to format it as a table.

<<splines-print-table, echo = TRUE, results='asis', echo = FALSE, cache = TRUE>>=
my.tab <- py$my_tab
print(xtable(my.tab, caption = paste("Some of the columns in the dataset.",
          "viol01\\_wife is the dependent variable and it records whether or",
       "not the woman in the couple has suffered violence from her husband.")), booktabs = TRUE)
@

\subsection{Data preparation for pymc}
\label{sec:data-prep-pymc}

Create an index starting from zero for each random term, the model will include a random intercept for «country« and for «cluster1«, and save the labels. Here the function «factorize()« from «pandas« is used.

<<splines-data.preparation.random.effects, engine='python', results = 'markup', cache = TRUE>>=
country_index, country_name = df["country"].factorize()
df["country_data"] = df["country"].astype("category").cat.codes

cluster_index, cluster_name = df["cluster1"].factorize()
df["cluster_id_unique_data"] = df["cluster1"].astype("category").cat.codes
@

\subsection{Apply dummy coding for the fixed effects}
\label{sec:apply-dummy-coding}

The «pandas« library in «python« has a function to create dummy variables, «get\_dummies()«. The argument «drop\_first=False« keeps the original columns, which often makes sense since otherwise the first value that happens to appear becomes the reference category. While the choice of reference category is generally not so important, in general make sure to choose a category that do not suffer from complete separation in an interaction term, since that makes the model fitting unnecessary hard. In this particular case, complete separation is not a concern.

<<splines-data.preparation.dummy.variables.list, engine='python', cache = TRUE>>=
dummy_vars = ["beat01_couple", "decide2_health", "decide2_purchases", "edudeviation", "couple_is_illiterate", "v149"]
@ 

<<splines-data.preparation.dummy.variables, engine='python', cache = TRUE>>=
df = pd.get_dummies(df, prefix=dummy_vars, columns=dummy_vars, drop_first=False)
@

\section{Create the splines}
The technique outlined here was published in \href{https://www.pymc.io/projects/examples/en/latest/howto/spline.html}{Joshua Cook's notebook on splines}. Cook, using an example where years was the numeric variable the splines were based on, wrote:

\begin{quote}
The knots are the boundaries of the spline, the name owing to how the individual lines will be tied together at these boundaries to make a continuous and smooth curve. The knots will be unevenly spaced over the years such that each region will have the same proportion of data. (see also \cite{benjamin_t_vincent_2022_7487077}).
\end{quote}

For this analysis we use «justifyIPV\_cluster« which captures how large proportion of the other women in the neighbourhood thinks that IPV can be legitimate, as the basis for the splines.

There are missing values in the dataset, drop rows with «NA« in at least one column.

<<splines-data.preparation.drop.na, engine='python', results = 'markup', cache = TRUE>>=
df = df.dropna().reset_index(drop=True)
@

Sort the rows based on «justifyIPV\_cluster«. This is needed because the code that produces the matrix «B« relies on «df« being in that order. We also need to reset the row names, or they will be used when we later concatenate the two objects into one with «pd.concat()«

<<splines-data.preparation.sort, engine='python', results = 'markup', cache = TRUE>>=
df = df.sort_values(by='justifyIPV_cluster', ascending=False).reset_index(drop=True)
@ 

Construct the matrix «B«, and the data frame version of the same data, «spline\_df«. «B« will be used as a model matrix for some of the parameters of the model, while «spline\_df« is convenient to have when we inspect the data visually. In the end, we want to replace «justifyIPV\_cluster« with a version of «B«, and for this purpose, «B\_df« is constructed.

<<splines-data.preparation.spline, engine='python', results = 'markup', cache = TRUE>>=
num_knots = 2
knot_list = np.quantile(df.justifyIPV_cluster, np.linspace(0, 1, num_knots))
@

The splines is generated by the function \href{https://patsy.readthedocs.io/en/latest/spline-regression.html}{«bs()«}, which is part of the «patsy« library.

Depending on if there will be an intercept in the model, use «include\_intercept=True« or «include\_intercept=False« in the call to «bs()«. Choose the latter unless the model only contains a single independent variable. In our case, the model will contain several other independent variables and a stand-alone intercept term is thus already included in the model. To illustrate what difference the intercept makes, compare figure \vref{fig:splines-data-preparation-inspect-spline} which is created without the intercept, and \vref{fig:splines-data-preparation-inspect-spline-intercept} which includes an intercept term.

<<splines-data-preparation-create-B, engine='python', results = 'markup', cache = TRUE>>=
B = dmatrix(
    "bs(justifyIPV_cluster, knots=knots, degree=3, include_intercept=False) - 1",
    {"justifyIPV_cluster": df.justifyIPV_cluster.values, "knots": knot_list[1:-1]},
    )
@ 

Figure \vref{fig:splines-data-preparation-inspect-spline} shows how a given value on «justifyIPV\_cluster« maps to a specific set of weights, without the spline intercept.

<<splines-data-preparation-inspect-spline, engine='python', echo = FALSE, results = 'markup', cache = TRUE, dev = "png", fig.cap = "For a given value on justifyIPV\\_cluster, the values of the curves indicate the weight of each parameter.">>=
spline_df = (
    pd.DataFrame(B)
    .assign(justifyIPV_cluster=df.justifyIPV_cluster.values)
    .melt("justifyIPV_cluster", var_name="spline_i", value_name="value")
)
color = plt.cm.magma(np.linspace(0, 0.80, len(spline_df.spline_i.unique())))
fig = plt.figure()
for i, c in enumerate(color):
    subset = spline_df.query(f"spline_i == {i}")
    subset.plot("justifyIPV_cluster", "value", c=c, ax=plt.gca(), label=i)
plt.legend(title="Spline Index", loc="upper center", fontsize=8, ncol=6);
@

A spline intercept functions as a normal intercept in that it captures the cases that have zero (in this case: zero \emph{on the variable that the splines are based on}, in the general case \emph{on all variables in the model}). Figure \vref{fig:splines-data-preparation-inspect-spline-intercept} shows how a given value on «justifyIPV\_cluster« maps to a specific set of weights, with a spline intercept.

<<splines-data-preparation-create-spline-intercept, engine='python', results = 'markup', cache = TRUE>>=
B_intercept = dmatrix(
    "bs(justifyIPV_cluster, knots=knots, degree=3, include_intercept=True) - 1",
    {"justifyIPV_cluster": df.justifyIPV_cluster.values, "knots": knot_list[1:-1]},
    )
@

<<splines-data-preparation-inspect-spline-intercept, engine='python', echo = FALSE, results = 'markup', cache = TRUE, dev = "png", fig.cap = "For a given value on justifyIPV\\_cluster, the values of the curves indicate the weight of each parameter. This version includes the intercept, see the black spline that has a high value at justifyIPV\\_cluster = 0; in fact all other splines have zero at this point, and the black spline has value 1 at that point.">>=
spline_intercept_df = (
    pd.DataFrame(B_intercept)
    .assign(justifyIPV_cluster=df.justifyIPV_cluster.values)
    .melt("justifyIPV_cluster", var_name="spline_i", value_name="value")
)
B_intercept_df = pd.DataFrame(B_intercept, columns=[f"spline, {i}" for i in range(B_intercept.shape[1])])
color = plt.cm.magma(np.linspace(0, 0.80, len(spline_intercept_df.spline_i.unique())))

fig = plt.figure()
for i, c in enumerate(color):
    subset = spline_intercept_df.query(f"spline_i == {i}")
    subset.plot("justifyIPV_cluster", "value", c=c, ax=plt.gca(), label=i)
plt.legend(title="Spline Index", loc="upper center", fontsize=8, ncol=6);
@

% We could fit the model using B as a second model matrix, but then we would need to keep track of B when we make predictions too, which is ok as long as we only use the builtin methods for predictions. But I want to be able do post-processing in R, and that is easier if there is a single model matrix. Therefore, add B as columns that goes into the main data object df. Joshua Cooks example is thus not enough for us anymore, and we must find a slightly different way to build the model. However, Cooks way of incorporating B in the model (by including a pm.math.dot(np.asarray(B, order="F"), w.T) was indeed short and clever, and we can leave it in.

<<splines-data.preparation.create.B_df, engine='python', results = 'markup', cache = TRUE>>=
B_df = pd.DataFrame(B, columns=[f"spline, {i}" for i in range(B.shape[1])])
@

In the final model, «B\_df« will replace «justifyIPV\_cluster«, and while it would be possible to refer to them as they are, it is \emph{convenient} to have single unified data object, especially if we want to predict using R later on. Such a unified data frame is aquired by concatenating «df« and «B\_df«.

<<splines-data.preparation.concatenate.B.and.df, engine='python', results = 'markup', cache = TRUE>>=
df = pd.concat([df, B_df], axis=1)
@

With that in place we can inspect how a given value of «justifyIPV\_cluster« translates to values on the new columns (named ``spline, 0''  to ``spline, 2''), see table \vref{tab:splines}. To produce this slice, only the rows in «df« with unique values on «justifyIPV\_cluster« was kept.

<<splines-create-new-slice, engine='python', cache = TRUE, echo = TRUE>>=
unique_rows = df.drop_duplicates(subset='justifyIPV_cluster').head(6)
my_tab_2 = unique_rows.iloc[:5, np.hstack((df.columns.get_loc("justifyIPV_cluster"), range(len(unique_rows.columns)-(num_knots + 1), len(unique_rows.columns))))]
@

<<splines-print.sorted.table, results='asis', echo = TRUE, cache = TRUE>>=
my.tab <- py$my_tab_2
library(xtable)
print(xtable(my.tab, caption = "justifyIPV\\_cluster and some of the columns that will replace it in the model. These rows represents the right most part of figure \\vref{fig:splines-data-preparation-inspect-spline}; at 0.98 the last curve is at value 0.5927 and the second curve is at value 0.3720.", digits = 4, label = "tab:splines"), booktabs = TRUE)
@

To actually predict probabilities, we also need to save the data frame that was used as a model matrix, since we have sorted the rows, and added columns for the splines. Note that this csv-file include variables for which we will not save the parameter estimates (the random effects in the model) and might also include variables never used in the model at all.

<<splines-save-the-model-matrix, engine='python', cache = TRUE>>=
df.to_csv("ipv-women-model_matrix.csv", index=False)
@ 


<<splines-show-the-model-matrix, engine='python', cache = TRUE, results = "markup">>=
df.columns
@ 

\section{Create the model}

Before creating the model in PyMC, let us define it mathematically.

The observed outcomes are modelled as samples from a Bernoulli distribution with probability \( p \), which represents the probability of success:

\[
y \sim \text{Bernoulli}(p)
\]

where \( y \in \{0,1\} \) is the observed outcome (0 for False or failure and 1 for True or success).

\subsection{Likelihood Function}

The likelihood $\mathcal{L}$ for a single observation given the model parameters \( \theta \) (which include the regression coefficients \( \beta \)) is:

\[
\mathcal{L}(\theta \mid y) = p^y (1 - p)^{1 - y}
\]

where \( p \) is the probability of success for that observation given the parameters of the model.

\subsection{Link Function and Linear Predictor}

The probability \( p \) is linked to the predictors via the sigmoid (logistic) function $\sigma(\eta)$:

\[
p = \sigma(\eta)
\]

where

\[
  \sigma(\eta) = \frac{1}{1 + e^{-\eta}}
\]

and \( \eta \) is the linear predictor, defined as:

\[
\eta = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \beta_3 x_3 + \dots + \beta_k x_k
\]

\subsection{Prior Distributions}

In a Bayesian framework, the model parameters are treated as random variables with prior distributions. A common choice is to use the normal distribution when defining priors for the regression coefficients:

\[
\beta_i \sim \mathcal{N}(\mu, \sigma^2)
\]

where we typically use weakly informative priors centered at zero (\(\mu = 0\)) with a large variance $\sigma^2$, to reflect our initial uncertainty about the parameter values.

\subsection{The likelihood of multiple observations}

On more piece of the puzzle is needed before we, in theory, could start evaluating the likelihood of different parameter sets of the model, given the observed data: how are multiple observations joined into one likelihood? The answer is that they are simply \emph{multiplied} together, the total likelihood is the \emph{product} of the individual likelihoods, which is the main point of the formula below:

The joint likelihood, given the model parameters \( \theta \), is:

\[
\mathcal{L}(\theta \mid y_1, y_2, \dots, y_n) = \prod_{i=1}^{n} p_i^{y_i} (1 - p_i)^{1 - y_i}
\]

where each \( p_i \) is computed from the regression equation:

\[
p_i = \sigma(\eta_i) = \frac{1}{1 + e^{-\eta_i}}
\]

and the linear predictor for each observation is:

\begin{equation}
  \eta_i = \beta_0 + \beta_1 x_{1i} + \beta_2 x_{2i} + \dots + \beta_k x_{ki}
  \label{lab:standard-regression}
\end{equation}


for $k$ predictors.

\begin{mdframed}[frametitle={Technical note: Likelihood vs Log-Likelihood}]
Since likelihood values are often very, very small (especially for large datasets), it's better to work with the \emph{log-likelihood}, which is less prone to issues with numerical instability than the way likelihood.

\[
\log \mathcal{L}(\theta \mid y_1, y_2, \dots, y_n) = \sum_{i=1}^{n} \left[ y_i \log p_i + (1 - y_i) \log (1 - p_i) \right]
\]

This log-likelihood is what PyMC (and most statistical software) maximizes when estimating parameters. 
\end{mdframed}

In a frequentist setting, model fitting is all about finding the \emph{point} in the parameter space with the \emph{maximum likelihood}. In a Bayesian framework, we are not so interesting in finding the point of highest likelihood, instead the sampling tries to explore the \emph{region(s)} of the parameter space with the highest likelilhood.

The regression equation \ref{lab:standard-regression} did not include any random effects, nor any splines, but as we shall see, in Bayesian statistics the distinction between random effects and fixed effects has no deeper meaning, it is a mere technicality that factor level fixed effects with $k$ number of levels are encoded into $k-1$ dummy-variables, whereas random terms are encoded with dummy variables for all levels of the random term.

The splines are also ``just ordinary'' $\beta$-coefficients. There is one thing that goes beyond the standard model though, the interaction between «beat01\_couple« and «justifyIPV\_cluster«, and since the latter is substituted by the splines in the model, it is worth spelling out how that is done. Consider table \vref{tab:splines}, which shows the values of «justifyIPV\_cluster« and the splines. Let us define $x_{1}, x_{2} and x_{3}$ as spline 0, spline 1 and spline 2 respectively. The other variable in the interaction, «beat01\_couple«, is also substituted in the model, in this case to dummy variables representing ``Wife accepts IPV'', ``Husband accepts IPV'', ``Both accept IPV'', let us say $x_{4}, x_{5}$ and $x_{6}$. Ignoring the other variables in the model, the variables relevant for «beat01\_couple« and «justifyIPV\_cluster« could be classified into three parts:

\begin{description}
  \item[spline 0] ${x_1} \beta{1}$
  \item[spline 1] ${x_2} \beta{2}$
  \item[spline 2] ${x_3} \beta{3}$
  \item[Wife accepts IPV] ${x_4} \beta{4}$
  \item[Husband accepts IPV] ${x_5} \beta{5}$
  \item[Both accept IPV] ${x_6} \beta{6}$
  \item[spline 0, Wife accepts IPV] $x_{1} x_{4} \beta_{7}$
  \item[spline 1, Wife accepts IPV] $x_{2} x_{4} \beta_{8}$
  \item[spline 2, Wife accepts IPV] $x_{3} x_{4} \beta_{9}$
    \item[spline 0, Husband accepts IPV] $x_{1} x_{5} \beta_{10}$
  \item[spline 1, Husband accepts IPV] $x_{2} x_{5} \beta_{11}$
  \item[spline 2, Husband accepts IPV] $x_{3} x_{5} \beta_{12}$    
    \item[spline 0, Both accepts IPV] $x_{1} x_{6} \beta_{13}$
  \item[spline 1, Both accepts IPV] $x_{2} x_{6} \beta_{14}$
  \item[spline 2, Both accepts IPV] $x_{3} x_{6} \beta_{15}$    
\end{description}

  Note that the first three rows above, ("spline 0", "spline 1" and "spline 2") will characterise the effect of  «justifyIPV\_cluster« for the couples where "No one accepts IPV", ie the reference category. Similarly, row 4-6 capture the effect of the attitudes of the couple in the scenario where «justifyIPV\_cluster« is zero.

Having this spelled out helps when we defining and naming the priors, however, since we have all the splines data in its own object «B«, we do not manually write down all these terms, we can just instruct «PYMC« to create all the possible combinations of spline and the dummy variables for «beat01\_couple«.

Creating a model in «pymc« involves multiple steps:

\begin{itemize}
\item create the model object
\item add \emph{priors} to the model object
\item add \emph{data} to the model object
\item add a formula that connects the observed outcome via a distribution to the predicted outcome, and produces a likelihood of the data, given the parameters - or rather, in more Bayesian terms, a posterior probability of the parameters, given the data.
\end{itemize}

For models with a large number of variables it is a good idea to deal with them in a systematic way, to make sure nothing is forgotten. I use to classify the variables into three main classes and work with one class at a time. Since the model is an object, which we can add parts to in separate steps, we do not need to do everything in one giant ``line'' of code, in fact we even add stuff to the model object in different chunks, in good \href{https://en.wikipedia.org/wiki/Literate_programming}{literate programming style}.

Before actually creating the model object, below defined as «my\_model«, it is a good idea to give human readable names to the parameters of the dummy variables, the levels of the random effects and the splines (for the continuous variables, naming happens naturally when defining the priors.

\subsection{Create the model object}

<<splines-fit-model-1, engine = "python", results = "markup", cache = TRUE>>=
import pymc as pm
coords={
    "couple_attitude_dims" : ["Husband justifys IPV", "Wife justifys IPV", "Both justify IPV"],
    "education_dims" : ["Incomplete primary", "Complete primary", "Incomplete secondary", "Complete_secondary", "Higher"],
    "decide_health_dims" : ["Health - husband decides", "Health - wife decides", "Healt - joint decisions"],
    "decide_purchase_dims" : ["Purchase - husband decides", "Purchase - wife decides", "Purchase - joint decisions"],
    "edudeviation_dims" : ["Husband has higer education", "Wife has higher education"],
    "literate_couple_dims" : ["Husband illiterate", "Wife illiterate", "Both can read"],
    "1|country_dims" : list(country_name),
    "1|cluster_dims" : list(cluster_name),
    "splines_dims": np.arange(B.shape[1])
}
my_model = pm.Model(coords=coords)
@

\subsection{Add priors to the model object}

Now follows a large number of chunks that taken together define the \emph{priors}, the \emph{data} and the \emph{regression formula}. The priors and the data can be defined in any order. Here we start with the priors, and deal with them one type at a time.

Define the priors, by choosing distribution (in closed form) with the relevant parameteters for each parameter, e.g. the normal distribution and its parameters $\mu$ and $\sigma$. When adding priors for the fixed effects factors, apply dummy coding, one scalar per term, shared sigmas for dummy variables with more than two levels. Start with the intercept.

<<splines-fit-model-2, engine = "python", results = "markup", cache = TRUE>>=
with my_model:
    Intercept = pm.Normal("Intercept", mu=0, sigma=5)
@

Now add the three dummy variables, use the names defined in «coords« for «couple\_attitude\_dims«.

<<splines-fit-model-3, engine = "python", results = "markup", cache = TRUE>>=
with my_model:
    couple_attitudes = pm.Normal("couple_attitudes", mu=0, sigma=1, dims = "couple_attitude_dims")
    interaction_terms = pm.Normal("interaction_terms", mu=0, sigma=1, dims = ["couple_attitude_dims", "splines_dims"])
    education = pm.Normal("education", mu=0, sigma=1, dims = "education_dims")
    decide_health = pm.Normal("decide_health", mu=0, sigma=1, dims = "decide_health_dims")
    decide_purchase = pm.Normal("decide_purchase", mu=0, sigma=1, dims = "decide_purchase_dims")
    edudeviation = pm.Normal("edudeviation", mu=0, sigma=1, dims = "edudeviation_dims")
    literate_couple = pm.Normal("literate_couple", mu=0, sigma=1, dims = "literate_couple_dims")
    iwi2 = pm.Normal("iwi2", mu=0, sigma=1)
    lnage_wife = pm.Normal("lnage_wife", mu=0, sigma=5)
    ln_numb_of_children = pm.Normal("ln_numb_of_children", mu=0, sigma=2)
    gdi = pm.Normal("gdi", mu=0, sigma=2)
    gni = pm.Normal("gni", mu=0, sigma=2)
    random_intercept_country = pm.Normal("1|country", mu=0, sigma=pm.HalfNormal("1|country_sigma", sigma=2.5), dims = "1|country_dims")
    random_intercept_cluster = pm.Normal("1|cluster", mu=0, sigma=pm.HalfNormal("1|cluster_sigma", sigma=2.5), dims = "1|cluster_dims")
    spline = pm.Normal("spline", mu=0, sigma=3, size=B.shape[1], dims="splines_dim")
@

Now that the priors are defined, inform pymc about where to find the data for the model matrix. Start with the random variables.

<<splines-fit-model-7, engine = "python", results = "markup", cache = TRUE>>=
with my_model:
    Z_country = pm.Data("Z_country", df["country_data"])
    Z_cluster = pm.Data("Z_cluster", df["cluster_id_unique_data"])
@

\subsection{Add data to the model object}
And the data for the fixed effects, first the factors.

\scalebox{.85}{\parbox{\textwidth}{

<<splines-fit-model-8, engine = "python", results = "markup", cache = TRUE>>=
with my_model:
    X_Husband_justifies_IPV = pm.Data("X_Husband_justifys_IPV", df["beat01_couple_Husband justifys IPV"])
    X_Wife_justifies_IPV = pm.Data("X_Wife_justifys_IPV", df["beat01_couple_Wife justifys IPV"])
    X_Both_justify_IPV = pm.Data("X_Both_justifys_IPV", df["beat01_couple_Both justify IPV"])
    X_Health_husband_decides = pm.Data("X_Health_husband_decides", df["decide2_health_husband decides"])
    X_Health_wife_decides = pm.Data("X_Health_wife_decides", df["decide2_health_wife decides"])
    X_Health_joint_decisions = pm.Data("X_Health_joint_decisions", df["decide2_health_joint decisions"])
    X_Purchases_husband_decides = pm.Data("X_Purchases_husband_decides", df["decide2_purchases_husband decides"])
    X_Purchases_wife_decides = pm.Data("X_Purchases_wife_decides", df["decide2_purchases_wife decides"])
    X_Purchases_joint_decisions = pm.Data("X_Purchases_joint_decisions", df["decide2_purchases_joint decisions"])
    X_Husband_higher_edu = pm.Data("X_Husband_higher_edu", df["edudeviation_Husband has higher edu."])
    X_Wife_higher_edu = pm.Data("X_Wife_higher_edu", df["edudeviation_Wife has higher edu."])
    X_Husband_illiterate = pm.Data("X_Husband_illiterate", df["couple_is_illiterate_Only wife can read"])
    X_Wife_illiterate = pm.Data("X_Wife_illiterate", df["couple_is_illiterate_Only husband can read"])
    X_Both_illiterate = pm.Data("X_Both_lliterate", df["couple_is_illiterate_No one can read"])
    X_incomplete_primary = pm.Data("X_incomplete_primary", df["v149_Incomplete primary"])
    X_complete_primary = pm.Data("X_complete_primary", df["v149_Complete primary"])
    X_incomplete_secondary = pm.Data("X_incomplete_secondary", df["v149_Incomplete secondary"])
    X_complete_secondary = pm.Data("X_complete_secondary", df["v149_Complete secondary"])
    X_higher = pm.Data("X_higher", df["v149_Higher"])
    X_iwi = pm.Data("X_iwi", df["iwi2"])
    X_lnage_wife = pm.Data("X_lnage_wife", df["lnage_wife"])
    X_ln_numb_of_children = pm.Data("X_ln_numb_of_children", df["ln_numb_of_children"])
    X_gdi = pm.Data("X_gdi", df["gdi_s"])
    X_gni = pm.Data("X_gni", df["gni_s"])
    B_ = pm.Data("B", np.asarray(B))
@

}}

\subsection{Formulate the regression equation}
Next step is to add a formula that connects the observed outcome via a distribution to the data and the priors.

<<splines-fit-model-9, engine = "python", results = "markup", cache = TRUE>>=
with my_model:
    theta_as_logit = Intercept + \
    X_Husband_justifies_IPV * couple_attitudes[0] + \
    X_Wife_justifies_IPV * couple_attitudes[1] + \
    X_Both_justify_IPV * couple_attitudes[2] + \
    X_Health_husband_decides * decide_health[0] + \
    X_Health_wife_decides * decide_health[1] + \
    X_Health_joint_decisions * decide_health[2] + \
    X_Purchases_husband_decides * decide_purchase[0] + \
    X_Purchases_wife_decides * decide_purchase[1] + \
    X_Purchases_joint_decisions * decide_purchase[2] + \
    X_Husband_higher_edu * edudeviation[0] + \
    X_Wife_higher_edu * edudeviation[1] + \
    X_Husband_illiterate * literate_couple[0] + \
    X_Wife_illiterate * literate_couple[1] + \
    X_Both_illiterate * literate_couple[2] + \
    X_incomplete_primary * education[0] + \
    X_complete_primary * education[1] + \
    X_incomplete_secondary * education[2] + \
    X_complete_secondary * education[3] + \
    X_higher * education[4] + \
    X_iwi * iwi2 + \
    X_lnage_wife * lnage_wife + \
    X_ln_numb_of_children * ln_numb_of_children + \
    X_gdi * gdi + \
    X_gni * gni + \
    random_intercept_country[Z_country] + \
    random_intercept_cluster[Z_cluster] + \
    pm.math.dot(B_, spline.T) + \
    pm.math.dot(B_, interaction_terms[0].T) * X_Husband_justifies_IPV + \
    pm.math.dot(B_, interaction_terms[1].T) * X_Wife_justifies_IPV + \
    pm.math.dot(B_, interaction_terms[2].T) * X_Both_justify_IPV

@

\subsection{Choose a distribution for the outcome}
Make it a logistic regression by tying the observed value to the model via the Bernoulli distribution.
<<splines-fit-model-11, engine = "python", results = "markup", cache = TRUE>>=
with my_model:
    theta_as_probability = pm.invlogit(theta_as_logit)
    y = pm.Data("y", df["viol01_wife"] == True)
    Y_obs = pm.Bernoulli("Y_obs", p=theta_as_probability, observed=y)
@

\subsection{Start sampling parameter values}
I think that during the tuning process, the «NUTS« sampler rescale the dimensions of the parameter space, so that the risk of divergencies is reduced and an appropriate step size is calibrated.

If you have a graphical processing unit (GPU) from «nvidia«, then install «jax« with gpu support. The code below will use the «numpyro\_nuts« sampler, which is built on top of «jax«, if «jax« is installed, and fall back to the native «pymc« «NUTS« sampler which uses CPU if «jax« is not installed. To be able to post process the parameter samples, these are saved  to disk with the function «dump()« in the library «pickle«. («batches=2« is my own invention, which reduces the RAM requirements on the GPU).

<<splines-fit-model-12, engine = "python", results = "markup", cache = TRUE, echo = TRUE>>=
import pickle
import pymc.sampling.jax
import arviz

try:
    with my_model:
        my_fit_pymc = pymc.sampling.jax.sample_numpyro_nuts(random_seed=1234, tune=200, draws=400, target_accept=0.8, chains = 2, chain_method='parallel', idata_kwargs=dict(log_likelihood=False), postprocessing_backend="cpu", progressbar = False)
except ImportError as e:
    with my_model:
        my_fit_pymc = pm.sample(random_seed=1234, tune=500, draws=200, target_accept=0.8, chains = 2, chain_method='parallel', cores=4, idata_kwargs=dict(log_likelihood=False), postprocessing_backend="cpu", progressbar = False)
pickle.dump(my_fit_pymc, open('ipv-women.pydata', 'wb'))

df_results = my_fit_pymc.to_dataframe(groups = "posterior", include_index=False)
df_results.drop(
    columns=[col for col in df_results.columns if "|" in str(col) or col in {"chain", "draw"}], 
    inplace=True
)
df_results.to_csv("ipv-women-splines.csv", index=False)
@

\section{Evaluate the model}
\label{sec:evaluate-model}

Inspect the r-hat statistics, and the High Density Intervals for the fixed effects parameters, see table \vref{tab:half-deciles}.

<<splines-evaluate-model-2, engine = "python", results = "markup", cache = TRUE>>=
import arviz
summary_df = arviz.summary(my_fit_pymc, var_names=["~country", "~cluster"], filter_vars="like")[["hdi_3%", "hdi_97%","r_hat"]]
summary_df.to_csv("spline-evaluate-model-2-summary.csv", index=True)
@

\begin{footnotesize}
<<splines-pretty.print.convergence, results="asis", echo = FALSE>>=
conv.tab <- read.csv("spline-evaluate-model-2-summary.csv")
colnames(conv.tab) <- c("Parameter", "HDI_3%", "HDI_97%","r_hat")
print(xtable(conv.tab, caption = "High Density Interval (HDI) and convergence statistics for fixed effect parameters.", label = "tab:convergence"), include.rownames = FALSE, booktabs = TRUE)
@ 
\end{footnotesize}

Show a trace plot of «couple\_attitudes«, note that these parameters only describe the effect of the attitudes in question when «justifyIPV\_cluster« is at zero, and also note that the reference category is ``No one accepts IVP''. Since there is no legend, this graph is not very informative, but it indicates that the model had enough tuning (or ``burn-in'') since the early samples are at the same level as the last samples; and the large fluctuations between nearby samples indicate that the parameter space is searched thoroughly, see figure \vref{fig:splines-evaluate-model-5}.

<<splines-evaluate-model-5, engine = "python", dev = "png", cache = TRUE, fig.cap = "Trace plot for the attitude of the couple.">>=
arviz.plot_trace(my_fit_pymc, var_names = ["couple_attitudes"], compact = True)
@

Import both the sampled parameters and the ``model matrix'' and make a clean version of the model matrix that \emph{only} contains the data that corresponds to the columns in params, and is in the \emph{right order}. 

<<splines-clean.mm>>=
ipv.mm <- read.csv("ipv-women-model_matrix.csv", check.names = FALSE)
params <- read.csv("ipv-women-splines.csv", check.names = FALSE)

my.recodes <- "'True' = 1; 'False' = 0"
## attitudes <- c("_Wife & husband accept IPV", "_Husband accept IPV", "_Wife accept IPV")
attitudes <- c("beat01_couple_Both justify IPV", "beat01_couple_Husband justifys IPV", "beat01_couple_Wife justifys IPV")

couple_attitudes <- cbind(sapply(c(attitudes), function(x) {
    car::recode(ipv.mm[[x]], recodes = my.recodes)                            
}, simplify = TRUE))

## dynamically adjust to any number of splines
## splines.iterator <- 0:py$num_knots
splines.iterator <- 0:2
my.spline.names <- paste0("spline, ", splines.iterator)
interaction_terms <- as.data.frame(sapply(c(attitudes), function(attitude) {
    sapply(my.spline.names, function(spline){
        return(car::recode(ipv.mm[[attitude]], recodes = my.recodes) *
            ipv.mm[[spline]])
    }, simplify = FALSE)
}, simplify = FALSE), check.names = FALSE)


education <- cbind(sapply(c("v149_Complete primary", "v149_Complete secondary", "v149_Higher", "v149_Incomplete primary", "v149_Incomplete secondary"), function(educational.level){
    car::recode(ipv.mm[[educational.level]], recodes = my.recodes)
}))

dummies <- cbind(sapply(c(
    "decide2_health_joint decisions", "decide2_health_husband decides", "decide2_health_wife decides",
    "decide2_purchases_husband decides", "decide2_purchases_joint decisions", "decide2_purchases_wife decides",
    "edudeviation_Husband has higher edu.", "edudeviation_Wife has higher edu.",
    "couple_is_illiterate_Both can read", "couple_is_illiterate_Only wife can read", "couple_is_illiterate_Only husband can read"
    ), function (dummy){
        car::recode(ipv.mm[[dummy]], recodes = my.recodes)        
    }))

as.is <- ipv.mm[c("iwi2", "lnage_wife", "ln_numb_of_children", "gdi_s", "gni_s", my.spline.names)]

my.mm <- cbind(Intercept = rep(1, nrow(ipv.mm)), couple_attitudes, interaction_terms, education, dummies, as.is)

## get the sample means
my.means <- apply(my.mm, 2, mean)

params.matrix <- as.matrix(params)
mean.matrix <- as.matrix(my.means)
@

Build the grid of values at which to generate predicted probabilities for each level of the factor variable that captures the attitudes of the couple. Even if splines have replaced the variable «justifyIPV\_cluster«, proceed as normal by finding relevant values on «justifyIPV\_cluster«, e.g. all non-extreme half-deciles, and for each interesting value on «justifyIPV\_cluster« find the corresponding set of values by extracting the values for the splines for cases that have the decile value on «justifyIPV\_cluster«. This is why «justifyIPV\_cluster« was retained in the model matrix even if it was not used when the model was fit to data.

<<splines-find-interesting.points>>=
quantiles <- quantile(ipv.mm$justifyIPV_cluster, probs = seq(from = 0,  to = 1, by = 0.01))

## Find the observed value closest to the quantile
these <- sapply(quantiles, function(x) { which.min(abs(ipv.mm$justifyIPV_cluster - x)) })
interesting.points.temp <- ipv.mm[these, c("justifyIPV_cluster", my.spline.names)]
keep.these <- which(duplicated(interesting.points.temp) == FALSE)
interesting.points <- interesting.points.temp[keep.these, ]
quantiles <- quantiles[keep.these]
@

<<splines-show-interesting.points, echo = FALSE, results="asis">>=
print(xtable(interesting.points[seq(from = 1, to = nrow(interesting.points), length.out = 10), ], label = "tab:half-deciles", caption = "Some of the points of «justifyIPV\\_cluster« and the corresponding values on the splines used when predicting."), include.rownames = FALSE, booktabs = TRUE)
@

Build one small model matrix for each level of the factor variable.
\begin{itemize}
\item Start with a copy of the mean matrix, replicated as many times as there are rows in the  object «quantiles«.
\item Copy the splines data from the object «interesting.points«.
\item Set all dummies to 0.
\item Loop over the possible values on the factor variable, including the reference category  
  \begin{itemize}
  \item Change the dummy for the current level to 1.
  \item Create the data for the interaction by multiplying the dummies and the splines data.
  \end{itemize}
\end{itemize}

<<splines-mm-to-predict-for>>=
mm.by.attitude.f <- function(this.attitude){
    ## Duplicate the mean matrix
    mean.matrix.replicated <- do.call(rbind, replicate(length(quantiles), t(mean.matrix), simplify = FALSE))
    ## Copy the values of splines
    mean.matrix.replicated[, my.spline.names] <- as.matrix(interesting.points[, my.spline.names])
    ## Set the dummies of the focal variable to 0 or 1
    for(dummy.var in attitudes){
        if(dummy.var == this.attitude){
            mean.matrix.replicated[, dummy.var] <- rep(1, length(quantiles))
        } else {
            mean.matrix.replicated[, dummy.var] <- rep(0, length(quantiles))
        }
    }
    ## Interaction terms
    interaction_terms <- unlist(sapply(c(attitudes), function(attitude) {
        sapply(my.spline.names, function(spline){
            return(mean.matrix.replicated[, attitude] * mean.matrix.replicated[, spline])
        }, simplify = FALSE)
    }, simplify = FALSE), recursive = FALSE)
    ## overwrite values in mean.matrix.replicated with the newly calculated values
    for(interaction.term in names(interaction_terms)){
        mean.matrix.replicated[, interaction.term] <- interaction_terms[[interaction.term]]
    }
    return(mean.matrix.replicated)
}
mms <- sapply(c("None justifys IPV", attitudes), mm.by.attitude.f, simplify = FALSE)
@

Verify that the parameters and the values are aligned, see the result in table \vref{tab:alignment}.

<<splines-check.alignment>>=
check.alignment.tab <- data.frame(Parameters = dimnames(params.matrix)[[2]],
                                  Values = dimnames(mms[[1]])[[2]])
@ 

\begin{footnotesize}
<<splines-verify-alignment, results="asis", echo = FALSE>>=
library(xtable)
print(xtable(check.alignment.tab, label = "tab:alignment", caption = "Verify that the model matrix and the parameters matrix are aligned, ie that the row ordering is the same in both."), booktabs = TRUE)
@
\end{footnotesize}


\subsection{Predict}
\label{sec:predict}

Generate the predicted probabilities.

<<splines-predict>>=
my.probs <- c(0.025, 0.5, 0.975)
results <- sapply(mms, function(my.mm){
    apply(plogis(params.matrix %*% t(my.mm)), 2, quantile, probs = my.probs)
}, simplify = FALSE)
@

\subsection{Visualise the effects}
\label{sec:visualise-effects}

Plot the predicted probabilities.

<<splines-plot-predictions, fig.cap = "Predicted probabilities for a woman to be exposed to IPV conditioned on the attitudes in the couple and the attitudes of the other women in the local area.", fig.width = 6, fig.align = "center">>=
par(mar = c(4, 5, 5, 14))
plot(y = results[["None justifys IPV"]]["50%",],
     x = interesting.points[["justifyIPV_cluster"]],
     xlab = "Neighbourhood justification of IPV",
     ylab = "Probability of IPV",
     type = "l", col = "red", ylim = c(min(unlist(results)), max(unlist(results))),
     lwd = 1)
grid()
my.cols <- c("red", "darkgreen", "lightgreen", "orange")
my.alpha.cols <- sapply(my.cols, transparent, alpha = 0.6)
my.names <- c("None justifys IPV", attitudes)
for(i in 1:length(my.names)){
    polygon(y = c(results[[my.names[i]]]["2.5%",], rev(results[[my.names[i]]]["97.5%",])),
            x = c(interesting.points[["justifyIPV_cluster"]], rev(interesting.points[["justifyIPV_cluster"]])), col = my.alpha.cols[i], border = NA)
    lines(y = results[[my.names[i]]]["50%",],
          x = interesting.points[["justifyIPV_cluster"]],
          col = my.cols[i], lwd = 1, lty = 1)
}

legend("right",
       title = "Justifications in the couple",
       legend = c("No one justifies IPV", "Husband justifies IPV", 
                  "Wife justifies IPV", "Wife \\& husband justify IPV"), 
       col = c("red", "lightgreen", "orange", "darkgreen"), 
       lwd = 2, 
       lty = 1, 
       bty = "n", 
       ncol = 1,
       inset = c(-.8, 0),
       xpd = TRUE
)

@

\bibliographystyle{apacite}
\bibliography{references}

\end{document}
